import type { Metadata } from "next";

import "./globals.css";
import { fontLogo, fontSans, fontSerif } from "@/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressContentEditableWarning suppressHydrationWarning>
      <body
        className={cn(
          "flex min-h-screen flex-col bg-background antialiased",
          fontSans.variable,
          fontSerif.variable,
          fontLogo.variable
        )}
      >
        <Cursor />
        <SanityLive />
        {children}
      </body>
    </html>
  );
}
